# This is a basic workflow to help you get started with Actions

name: Firebase hosting deploy

# Controls when the action will run. Triggers the workflow on push
# events but only for the master branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    # And of course we need to goto our functions folder to deploy
    - name: Install npm packages
      run: |
        npm install
    - name: Generate Environment Variables File for Production
      run: |
        touch .env.production
        echo "VITE_FB_API_KEY=${{ secrets.VITE_FB_API_KEY }}" >> .env.production
        echo "VITE_FB_AUTH_DOMAIN=${{ secrets.VITE_FB_AUTH_DOMAIN }}" >> .env.production
        echo "VITE_FB_DATABASE_URL=${{ secrets.VITE_FB_DATABASE_URL }}" >> .env.production
        echo "VITE_FB_PROJECT_ID=${{ secrets.VITE_FB_PROJECT_ID }}" >> .env.production
        echo "VITE_FB_STORAGE_BUCKET=${{ secrets.VITE_FB_STORAGE_BUCKET }}" >> .env.production
        echo "VITE_FB_MESSAGING_SENDER_ID=${{ secrets.VITE_FB_MESSAGING_SENDER_ID }}" >> .env.production
        echo "VITE_FB_APP_ID=${{ secrets.VITE_FB_APP_ID }}" >> .env.production
        echo "VITE_FB_MESEAUREMENT_ID=${{ secrets.VITE_FB_MESEAUREMENT_ID }}" >> .env.production
    - name: Bulid web
      run: |
        npm run build
        
    # Deploying the functions to firebase
    - name:  Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
          args: deploy --only hosting
      env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
